[package]
authors = ["Litentry dev"]
edition = "2021"
name = "lc-credentials-tee"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
futures = { version = "0.3.8", optional = true }
hex = { version = "0.4.3", optional = true }
url = { version = "2.0.0", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
thiserror = { version = "1.0.26", optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# litentry
parentchain-primitives = { package = "primitives", path = "../../../primitives", default-features = false }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# internal dependencies
ita-stf = { path = "../../../app-libs/stf", default-features = false }
itp-ocall-api = { path = "../../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { path = "../../../core-primitives/substrate-sgx/externalities", default-features = false }
itp-stf-executor = { path = "../../../core-primitives/stf-executor", default-features = false }
itp-storage = { path = "../../../core-primitives/storage", default-features = false }
itp-top-pool-author = { path = "../../../core-primitives/top-pool-author", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../core-primitives/utils", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32", default-features = false }

lc-stf-task-sender = { path = "../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
mockserver = []
sgx = [
    "futures_sgx",
    "hex-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "ita-stf/sgx",
    "itp-stf-executor/sgx",
    "itp-sgx-externalities/sgx",
    "itp-top-pool-author/sgx",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "futures",
    "hex",
    "log/std",
    "serde/std",
    "serde_json/std",
    "thiserror",
    "url",
    "ita-stf/std",
    "itp-types/std",
    "itp-utils/std",
    "itp-stf-executor/std",
    "itp-top-pool-author/std",
    "itp-sgx-externalities/std",
    "itp-storage/std",
    "sp-std/std",
    "sp-io/std",
    "sp-runtime/std",
    "frame-support/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
]
