[package]
authors = ["Litentry Dev"]
edition = "2021"
name = "lc-credentials-tee"
version = "0.1.0"

[dependencies]
# std dependencies
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
hex = { version = "0.4.3", optional = true }
thiserror = { version = "1.0.26", optional = true }
url = { version = "2.0.0", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# internal dependencies
itc-rest-client = { path = "../../../core/rest-client", default-features = false }

# sgx dependencies
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# litentry
litentry-primitives = { path = "../../primitives", default-features = false }
parentchain-primitives = { package = "primitives", path = "../../../../primitives", default-features = false }


[dev-dependencies]
httpmock = "0.6"
lc-mock-server = { path = "../mock-server" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.32", default-features = false }

[features]
default = ["std"]
mockserver = []
sgx = [
    "hex-sgx",
    "thiserror_sgx",
    "url_sgx",
    "sgx_tstd",
    "itc-rest-client/sgx",
    "litentry-primitives/sgx",
]

std = [
    "codec/std",
    "hex",
    "thiserror",
    "url",
    "itc-rest-client/std",
    "log/std",
    "serde/std",
    "serde_json/std",
    "litentry-primitives/std",
]
